#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

#Merge non-interactively
export GIT_MERGE_AUTOEDIT=no

git flow release start -F $1
sed --in-place "s/^__version__ = .*/__version__ = '$1'/g" vam/__init__.py
git add vam/__init__.py
git commit -m "Update version number"
git flow release finish -F -p -m "Release version $1" $1
